= DebugTrace-net

link:README_ja.asciidoc[[Japanese]]

*DebugTrace-net* is a library that outputs trace logs when debugging .NET programs. It corresponds to https://docs.microsoft.com/en-us/dotnet/standard/net-standard[.NET Standard 2.0]. +
By embedding `Trace.Enter()` and `Trace.Leave()` at the start and end of methods, you can output the execution status of the program under development to the log.

=== 1. Features

* Automatically outputs caller's *class name*, *method name*, *source file name* and *line number*.
* *Automatically indents* the log with nesting methods and objects.
* *Automatically breaks* at the output of values.
* Automatically output logs when *changing threads*.
* Uses *reflection* to output objects of classes that do not implement `ToString` method.
* You can customize the output content in `DebugTrace.properties`.
* There is *no dependency library* if you output to the console
* You can use the following logging library.
    ** https://logging.apache.org/log4net/[log4net]
    ** http://nlog-project.org/[NLog]

=== 2. Install

Search `DebugTrace` packege on NuGet and install it. +
If you output logs using https://logging.apache.org/log4net/[log4net] or http://nlog-project.org/[NLog],
install `DebugTrace.Log4net` or `DebugTrace.NLog` package.
`DebugTrace.Log4net` and `DebugTrace.NLog` package corresponds to .NET Framework 4.7 instead of https://docs.microsoft.com/en-us/dotnet/standard/net-standard[.NET Standard].

=== 3. How to use

Do the following for debug target and related methods.

. Insert `Trace.Enter()` at the beginning of methods.
. Insert `Trace.Leave()` at the end of methods or just before the `return` statements.
. Insert `Trace.Print("foo", foo)` or `Trace.Print(nameof(foo), foo)` to output arguments, local variables and return value to the log if necessary.

The following are examples of C# and Visual Basic source used DebugTrace-net methods and the log of when it has been executed.

[source,csharp]
.ReadmeExample.cs
----
using System;
using static DebugTrace.CSharp; // for Debugging

namespace Readme {
    /// <summary>ReadmeExample</summary>
    public class ReadmeExample {
        public static void Main(string[] args) {
            Trace.Enter(); // for Debugging

            var contact = new Contact(1, "Akane", "Apple", new DateTime(1991, 2, 3));
            Trace.Print(nameof(contact), contact); // for Debugging

            Trace.Leave(); // for Debugging
        }
    }

    /// <summary>Entity</summary>
    public class Entity {
        public int ID;

        public Entity(int id) {
            ID = id;
        }
    }

    /// <summary>ContactBase</summary>
    public class ContactBase : Entity {
        public string FirstName;
        public string LastName;

        public ContactBase(int id, string firstName, string lastName) : base(id) {
            FirstName = firstName; LastName  = lastName ;
        }
    }

    /// <summary>Contact</summary>
    public class Contact : ContactBase {
        public DateTime Birthday;

        public Contact(int id, string firstName, string lastName, DateTime birthday) : base(id, firstName, lastName) {
            Birthday  = birthday ;
        }
    }
}
----

.Console output / C#
----
2018-03-28 01:10:51.413 ______________________________ Thread 1 ______________________________
2018-03-28 01:10:51.413
2018-03-28 01:10:51.473 Enter Readme.ReadmeExample.Main(String[] args) (ReadmeExample.cs:8)
2018-03-28 01:10:51.500 | contact = Readme.Contact {
2018-03-28 01:10:51.500 |   ____ Readme.Entity ____
2018-03-28 01:10:51.501 |   ID: 1,
2018-03-28 01:10:51.501 |   ____ Readme.ContactBase ____
2018-03-28 01:10:51.501 |   FirstName: "Akane", LastName: "Apple",
2018-03-28 01:10:51.501 |   ____ Readme.Contact ____
2018-03-28 01:10:51.501 |   Birthday: 1991-02-03 12:00:00.000,
2018-03-28 01:10:51.501 | } (ReadmeExample.cs:11)
2018-03-28 01:10:51.509 Leave Readme.ReadmeExample.Main(String[] args) (ReadmeExample.cs:13)
----

[source,vb.net]
.ReadmeExample.vb
----
Imports System
Imports DebugTrace.VisualBasic ' for Debugging

Namespace Global.Readme
    ''' <summary>ReadmeExample</summary>
    Public Class ReadmeExample
        Public Shared Sub Main(args As String())
            Trace.Enter() ' for Debugging

            Dim contact = New Contact(1, "Akane", "Apple", New DateTime(1991, 2, 3))
            Trace.Print(NameOf(contact), contact) ' for Debugging

            Trace.Leave() ' for Debugging
        End Sub
    End Class

    ''' <summary>Entity</summary>
    Public Class Entity
        Public Property ID As Integer

        Public Sub New(id_ As Integer)
            ID = id_
        End Sub
    End Class

    ''' <summary>ContactBase</summary>
    Public Class ContactBase : Inherits Entity
        Public Property FirstName As String
        Public Property LastName As String

        Public Sub New(id_ As Integer, firstName_ As String, lastName_ As String)
            MyBase.New(id_)
            FirstName = firstName_ : LastName = lastName_
        End Sub
    End Class

    ''' <summary>Contact</summary>
    Public Class Contact : Inherits ContactBase
        Public Birthday As DateTime

        Public Sub New(id_ As Integer, firstName_ As String, lastName_ As String, birthday_ As DateTime)
            MyBase.New(id_, firstName_, lastName_)
            Birthday = birthday_
        End Sub
    End Class
End Namespace
----

.Console output / Visual Basic
----
2018-03-28 02:30:08.528 ______________________________ Thread 1 ______________________________
2018-03-28 02:30:08.528
2018-03-28 02:30:08.591 Enter Readme.ReadmeExample.Main(String[] args) (ReadmeExample.vb:8)
2018-03-28 02:30:08.619 | contact = Readme.Contact {
2018-03-28 02:30:08.619 |   ____ Readme.Entity ____
2018-03-28 02:30:08.619 |   ID: 1,
2018-03-28 02:30:08.619 |   ____ Readme.ContactBase ____
2018-03-28 02:30:08.619 |   FirstName: "Akane", LastName: "Apple",
2018-03-28 02:30:08.620 |   ____ Readme.Contact ____
2018-03-28 02:30:08.620 |   Birthday: 1991-02-03 12:00:00.000,
2018-03-28 02:30:08.620 | } (ReadmeExample.vb:11)
2018-03-28 02:30:08.627 Leave Readme.ReadmeExample.Main(String[] args) (ReadmeExample.vb:13)
----

=== 3. Interfaces and Classes

There are mainly the following interfaces and classes.

[options="header", width="100%"]
.Interfaces and Classes
|===
|Name     |Super Class or Implemented Interfaces|Description
|`DebugTrace.ITrace`       |_None_              |Trace processing interface
|`DebugTrace.TraceBase`    |`DebugTrace.ITrace` |Trace processing base class
|`DebugTrace.CSharp`       |`DebugTrace.Trace`  |Trace processing class for C#
|`DebugTrace.VisualBasic`  |`DebugTrace.Trace`  |Trace processing class for VisualBasic
|`DebugTrace.ILogger`      |_None_              |Log output interface
|`DebugTrace.Console`      |`DebugTrace.ILogger`|Abstract class that outputs logs to the console
|`DebugTrace.Console+Out`  |`DebugTrace.Console`|Class outputting logs to standard output
|`DebugTrace.Console+Error`|`DebugTrace.Console`|Class outputting logs to standard error output
|===

=== 4. Properties of DebugTrace.CSharp class and DebugTrace.VisualBasic class

`DebugTrace.CSharp` and `DebugTrace.VisualBasic` class has `Trace` property as an instance of its own type.

=== 5. Properties and methods of ITrace interface

It has the following properties and methods.

[options="header", width="60%"]
.Properties
|===
|Name|Description
|`IsEnabled`
|`true` if log output is enabled, `false` otherwise (`get` only)

|`LastLog`
|Last log string outputted (`get` only)

|===

[options="header"]
.Methods
|===
|Name|Arguments|Return Value|Description
|`ResetNest`
|_None_
|_None_
|Initializes the nesting level for the current thread.

|`Enter`
|_None_
|`int` thread ID
|Outputs method start to log.

|`Leave`
|`int threadId`: the thread ID (default: `-1`)
|_None_
|Outputs method end to the log.

|`Print`
|`string message`: the message
|_None_
|Outputs the message to the log.

|`Print`
|`Func<string> messageSupplier`: the function to return a message
|_None_
|Gets a message from `messageSupplier` and output it to the log.

|`Print`
|`string name`: the name of the value +
`object value`: the value
|_None_
|Outputs to the log in the form of `"Name = Value"`

|`Print`
|`string name`: the name of the value +
`Func<object> valueSupplier`:  the function to return a value
|_None_
|Gets a value from `valueSupplier` and output it to the log in the form of `"Name = Value"`.

|===

=== 6. Properties of *DebugTrace.properties* file

DebugTrace reads the `DebugTrace.properties` file in the same directory as DebugTrace.dll at startup.
You can specify following properties in the `DebugTrace.properties` file.  

[options="header"]
.DebugTrace.properties
|===
|Property Name|Value to be set|Default Value

|`Logger`
| *Logger* DebugTrace uses +
 +
`Log4net`: use Log4net +
`NLog`: use NLog +
`Console+Out`: Output to the console (stdout) +
`Console+Error`: Output to the console (stderr)
|`Console+Error`

|`LogLevel`
|*Log level* at log output +
 +
`Lo4jnet`: `All`, `Debug`, `Info`, `Warn`, `Error`, `Fatal`, `Off` +
`NLog`: `Trace`, `Debug`, `Info`, `Warn`, `Error`, `Off` +
|`Debug`

|`EnterString`
|The string output by `enter` method +
 +
`[Teal]#parameters#:` +
`{0}`: The class name of the caller +
`{1}`: The method name of the caller +
`{2}`: The file name of the caller +
`{3}`: The line number of the caller
|`Enter {0}.{1} ({2}:{3:D})`

|`LeaveString`
|The string output by `leave` method +
 +
`[Teal]#parameters#:` +
`{0}`: The class name of the caller +
`{1}`: The method name of the caller +
`{2}`: The file name of the caller +
`{3}`: The line number of the caller
|`Leave {0}.{1} ({2}:{3:D})`

|`ThreadBoundaryString`
|The string output in the *threads boundary*. +
 +
_parameters:_ +
`{0}`: The thread ID
|`\____\__\__\__\__\__\__\__\__\__\__\__\__\__ Thread {0} \__\__\__\__\__\__\__\__\__\__\__\__\__\____`

|`ClassBoundaryString`
|The string output in the *classes boundary*. +
 +
_parameters:_ +
`{0}`: The class name
|`\\____ {0} \____`

|`CodeIndentString`
|The string of one *code indent* +
`\s` _is change to a space character_
|`\|\s`

|`DataIndentString`
|The string of one *data indent* +
`\s` _is change to a space character_
|`\s\s`

|`LimitString`
|The *string* to represent that it has exceeded the *limit*
|`\...`

|`DefaultNameSpaceString` +
|The string replacing the default *namespace* part
|`\...`

|`NonPrintString` +
|The string of value in the case of properties that *do not output* the value
|`\***`

|`CyclicReferenceString`
|The string to represent that the *cyclic reference* occurs
|`\*\** Cyclic Reference \***`

|`VarNameValueSeparator`
|The separator string between the *variable name and value* +
`\s` _is change to a space character_
|`\s=\s`

|`KeyValueSeparator`
|The separator string between the *key and value* for Map object
and between the *property/field name and value* +
`\s` _is change to a space character_
|`:\s`

|`PrintSuffixFormat`
|Output format of `print` method suffix +
`\s` _is change to a space character_ +
 +
_parameters:_ +
`{0}`: The class name of the caller +
`{1}`: The method name of the caller +
`{2}`: The file name of the caller +
`{3}`: The line number of the caller
|`\s({2}:{3:D})`

|`DateTimeFormat`
|Output format of *date and time* +
 +
_parameters:_ +
`{0}`: The `DateTime` object +
|`{0:yyyy-MM-dd hh:mm:ss.fff}`

|`MaxDataOutputWidth`
|*Maximum* output *width of data*
|80

|`CollectionLimit`
|*Limit* value of `ICollection` elements to output
|512

|`StringLimit`
|*Limit* value of `string` characters to output
|8192

|`ReflectionNestLimit`
|*Limit* value of *reflection nest*
|4

|`NonPrintProperties` +
|Properties and fields *not to be output* +
value +
 +
`[Teal]#format#:` +
`<full class name>.<property or field name>`, +
`<full class name>.<property or field name>`, +
`\...`
|_Empty_

|`DefaultNameSpace` +
|Default *namespace* of your java source
|_None_

|`ReflectionClasses` +
|*Classe names* that output content by *reflection* even if `ToString` method is implemented
|_Empty_

|===

==== 6.1. *NonPrintProperties*, *NonPrintString*

DebugTrace use reflection to output object contents if the `ToString` method is not implemented.
If there are other object references, the contents of objects are also output.
However, if there is circular reference, it will automatically detect and suspend output.
You can suppress output by specifying the `NonPrintProperties` property and
can specify multiple values of this property separated by commas.  
The value of the property specified by `NonPrintProperties` are output as the string specified by `NonPrintString` (default: `\***`).

.Example of NonPrintProperties
----
NonPrintProperties = DebugTraceExample.Node.Parent
----

.Example of NonPrintProperties (Multiple specifications)
----
NonPrintProperties = \
    DebugTraceExample.Node.Parent,\
    DebugTraceExample.Node.Left,\
    DebugTraceExample.Node.Right
----

=== 7. Examples of using logging libraries

You can output logs using the following libraries besides console output.

[options="header", width="60%"]
.logging Libraries
|===
|Library Name|Required package  |API
|log4net     |DebugTrace.Log4net|.NET Framework 4.7
|NLog        |DebugTrace.NLog   |.NET Framework 4.7
|===

To use them, add the above package from NuGet.

The logger name of DebugTrace is `DebugTrace`.   

==== 7-1. log4net

[source,properties]
.Example of DebugTrace.properties
----
# DebugTrace.properties
Logger = Log4net
----

[source,csharp]
.Additional example of AssemblyInfo.cs
----
[assembly: log4net.Config.XmlConfigurator(ConfigFile=@"Log4net.config", Watch=true)]
----

[source,xml]
.Example of Log4net.config
----
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <log4net>
    <appender name="A" type="log4net.Appender.FileAppender">
      <File value="C:/Logs/DebugTrace/Log4net.log" />
      <AppendToFile value="true" />
      <layout type="log4net.Layout.PatternLayout">
        <ConversionPattern value="%date [%thread] %-5level %logger %message%n" />
      </layout>
    </appender>
    <root>
      <level value="DEBUG" />
      <appender-ref ref="A" />
    </root>
  </log4net>
</configuration>
----

==== 7-2. NLog

[source,properties]
.Example of DebugTrace.properties
----
# DebugTrace.properties
Logger = NLog
----

[source,xml]
.Example of NLog.config
----
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="C:/Logs/DebugTrace/NLog-internal.log">
  <targets>
    <target xsi:type="File" name="f" fileName="C:/Logs/DebugTrace/NLog.log"
            layout="${longdate} [${threadid}] ${uppercase:${level}} ${logger} ${message}" />
  </targets>
  <rules>
    <logger name="*" minlevel="Debug" writeTo="f" />
  </rules>
</nlog>
----

=== 8. License

link:LICENSE[The MIT License (MIT)]

[gray]#_(C) 2018 Masato Kokubo_#
